/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Page,
} from './store/model/wf/Page';

export namespace Components {
  interface MyComponent {
    'first': string;
    'last': string;
    'middle': string;
  }
  interface PolarisButton {
    'next': string;
    'title': string;
  }
  interface PolarisLabel {}
  interface PolarisSelect {
    'value': any;
  }
  interface SiriusPage {
    'page': Page;
  }
  interface SiriusWf {}
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLPolarisButtonElement extends Components.PolarisButton, HTMLStencilElement {}
  var HTMLPolarisButtonElement: {
    prototype: HTMLPolarisButtonElement;
    new (): HTMLPolarisButtonElement;
  };

  interface HTMLPolarisLabelElement extends Components.PolarisLabel, HTMLStencilElement {}
  var HTMLPolarisLabelElement: {
    prototype: HTMLPolarisLabelElement;
    new (): HTMLPolarisLabelElement;
  };

  interface HTMLPolarisSelectElement extends Components.PolarisSelect, HTMLStencilElement {}
  var HTMLPolarisSelectElement: {
    prototype: HTMLPolarisSelectElement;
    new (): HTMLPolarisSelectElement;
  };

  interface HTMLSiriusPageElement extends Components.SiriusPage, HTMLStencilElement {}
  var HTMLSiriusPageElement: {
    prototype: HTMLSiriusPageElement;
    new (): HTMLSiriusPageElement;
  };

  interface HTMLSiriusWfElement extends Components.SiriusWf, HTMLStencilElement {}
  var HTMLSiriusWfElement: {
    prototype: HTMLSiriusWfElement;
    new (): HTMLSiriusWfElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'polaris-button': HTMLPolarisButtonElement;
    'polaris-label': HTMLPolarisLabelElement;
    'polaris-select': HTMLPolarisSelectElement;
    'sirius-page': HTMLSiriusPageElement;
    'sirius-wf': HTMLSiriusWfElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }
  interface PolarisButton {
    'next'?: string;
    'title'?: string;
  }
  interface PolarisLabel {}
  interface PolarisSelect {
    'value'?: any;
  }
  interface SiriusPage {
    'page'?: Page;
  }
  interface SiriusWf {}

  interface IntrinsicElements {
    'my-component': MyComponent;
    'polaris-button': PolarisButton;
    'polaris-label': PolarisLabel;
    'polaris-select': PolarisSelect;
    'sirius-page': SiriusPage;
    'sirius-wf': SiriusWf;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'polaris-button': LocalJSX.PolarisButton & JSXBase.HTMLAttributes<HTMLPolarisButtonElement>;
      'polaris-label': LocalJSX.PolarisLabel & JSXBase.HTMLAttributes<HTMLPolarisLabelElement>;
      'polaris-select': LocalJSX.PolarisSelect & JSXBase.HTMLAttributes<HTMLPolarisSelectElement>;
      'sirius-page': LocalJSX.SiriusPage & JSXBase.HTMLAttributes<HTMLSiriusPageElement>;
      'sirius-wf': LocalJSX.SiriusWf & JSXBase.HTMLAttributes<HTMLSiriusWfElement>;
    }
  }
}


