/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    'first': string;
    'last': string;
    'middle': string;
  }
  interface SiriusWf {}
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLSiriusWfElement extends Components.SiriusWf, HTMLStencilElement {}
  var HTMLSiriusWfElement: {
    prototype: HTMLSiriusWfElement;
    new (): HTMLSiriusWfElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'sirius-wf': HTMLSiriusWfElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }
  interface SiriusWf {}

  interface IntrinsicElements {
    'my-component': MyComponent;
    'sirius-wf': SiriusWf;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'sirius-wf': LocalJSX.SiriusWf & JSXBase.HTMLAttributes<HTMLSiriusWfElement>;
    }
  }
}


