/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {}
  interface PolarisWf {}
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLPolarisWfElement extends Components.PolarisWf, HTMLStencilElement {}
  var HTMLPolarisWfElement: {
    prototype: HTMLPolarisWfElement;
    new (): HTMLPolarisWfElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'polaris-wf': HTMLPolarisWfElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {}
  interface PolarisWf {}

  interface IntrinsicElements {
    'my-component': MyComponent;
    'polaris-wf': PolarisWf;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'polaris-wf': LocalJSX.PolarisWf & JSXBase.HTMLAttributes<HTMLPolarisWfElement>;
    }
  }
}


